services:
  - type: web
    name: wall-clock
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn server:app --bind 0.0.0.0:$PORT --workers 1 --threads 2
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
